version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      # default shell is Powershell
      - run:
          command: curl -L 'https://github.com/k3s-io/k3s/releases/download/v1.19.4%2Bk3s2/k3s' --output k3s
          shell: bash.exe
      - run:
          command: chmod +x k3s
          shell: bash.exe
      - run:
          command: ./k3s server
          shell: bash.exe